# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'WebServiceHitDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebServiceHitDemo
 	pod 'Alamofire', '4.1'
  pod 'AlamofireImage', '3.2'
  pod 'SwiftyJSON'

end
